### ISSUE TITLE
How can I know if one URL is in cache?

### ISSUE THREAD

**Issue by rmelian2014** [msching/AVPlayerCacheSupport#8]
Sorry if this is a dumb question but I am puzzled with this, your library have a simple method to know if an url is in cache already?

Thanks in advance!

**Comment by msching** [comment]
not yet, so you have to manage your url and cache file path yourself.

**Comment by msching** [comment]
BTW, AVAssetResourceLoaderDelegate doesn't work as expected in real device.
-resourceLoader:didCancelLoadingRequest: works fine on Simulator, but NOT called in real device.
So this lib may have some problem in real device.

**Comment by rmelian2014** [comment]
OK, thanks for the fast reply!!!
